from langchain_groq import ChatGroq
import os
from dotenv import load_dotenv


# LOAD ENVIRONMENT VARIABLE

# GROQ_API_KEY=your_api_key_here
load_dotenv()



# GET GROQ API KEY


# Read the Groq API key from the environment.
groq_api_key = os.getenv("GROQ_API_KEY")


# Check whether the API key exists.
if not groq_api_key:
    raise ValueError(
        "GROQ_API_KEY is not set. "
        "Please add it to your .env file."
    )


# CREATE LLM

# ChatGroq creates a connection to the Groq-hosted LLM.
#
# temperature=0.1:
# Low temperature makes the answer more focused and
# deterministic, which is useful for RAG.
#
# max_tokens=1024:
# Limits the maximum length of the generated answer.
llm = ChatGroq(
    api_key=groq_api_key,
    model="openai/gpt-oss-20b",
    temperature=0.1,
    max_tokens=1024
)


# LLM GENERATION FUNCTION


def generate_answer(prompt: str) -> str:
    """
    Send the prompt to the LLM and return the generated answer.

    Parameters:
        prompt (str):
            Complete prompt containing the instructions,
            retrieved context, and user's question.

    Returns:
        str:
            Answer generated by the LLM.
    """

    # Send the prompt to the Groq LLM.
    response = llm.invoke(prompt)

    # ChatGroq returns an AIMessage object.
    # response.content contains the actual generated text.
    return response.content