from src.rag1.hybrid_retriever import HybridRetriever
from src.rag1.prompt import PromptBuilder
from src.rag1.llm import generate_answer


class RAGPipeline:
    def __init__(self,retriever: HybridRetriever,prompt_builder: PromptBuilder):
        """
        Initialize the RAG pipeline.

        Parameters:
            retriever:
                HybridRetriever object responsible for
                FAISS + BM25 + RRF retrieval.

            prompt_builder:
                PromptBuilder object responsible for
                creating the LLM prompt.
        """

        # Store the hybrid retriever.
        self.retriever = retriever

        # Store the prompt builder.
        self.prompt_builder = prompt_builder

    def run(self, query: str, top_k: int = 5):
        """
        Run the complete RAG pipeline.

        Parameters:
            query:
                User's question.

            top_k:
                Number of relevant chunks to retrieve.

        Returns:
            Final answer generated by the LLM.
        """

        #  RETRIEVE
        results = self.retriever.retrieve(
            query=query,
            top_k=top_k
        )
        # If no documents were retrieved,
        # don't call the LLM unnecessarily.
        if not results:
            return "No relevant context found to answer the question."

        #  BUILD CONTEXT
        context = self.retriever.build_context(results)

        # Check whether context is empty.
        if not context.strip():
            return "No relevant context found to answer the question."
        
        # STEP 3: BUILD PROMPT
        prompt = self.prompt_builder.build_prompt(query=query,context=context)

        # STEP 4: GENERATE ANSWER
        answer = generate_answer(prompt)
        return answer,results

